.PHONY: clean All

All:
	@echo "----------Building project:[ po - Debug ]----------"
	@cd "po" && "$(MAKE)" -f  "po.mk"
clean:
	@echo "----------Cleaning project:[ po - Debug ]----------"
	@cd "po" && "$(MAKE)" -f  "po.mk" clean
